import Head from "next/head";
import Link from 'next/link';
import { BsFillMoonStarsFill } from "react-icons/bs";
import { useState } from "react";
import Image from "next/image";
import bimbel from "../public/bimbel.png";
import gunung from "../public/gunung.png";
import tsunami1 from "../public/tsunami1.png";
import tsunami2 from "../public/tsunami2.png";
import bangkit from "../public/bangkit.jpeg";
import flask from "../public/flask.jpg";
import onlineshop2 from "../public/onlineshop2.png";
import bookshelf from "../public/bookshelf.png";
import computershop from "../public/computershop.png";
import stopwatch from "../public/stopwatch.png";
import calorease from "../public/calorease.png";

export default function Portfolio() {
    const [darkMode, setDarkMode] = useState(false);
    const webProjects = [
        {
            title: "CalorEase",
            image: calorease,
            description: "Application that focusing on helping people control the number of calories eaten each day by scanning the food image after that can get the nutrition data like calories,fat,protein,etc",
            link: "https://github.com/orgs/CalorEase/repositories"
        },
        {
            title: "Tsunami Warning Center",
            image: tsunami1,
            description: "Website for Tsunami Disaster and Warning Center with BMKG API on Realtime Earthquake data +5.0 Magnitudo and Realtime Maps with GeoJSON prevention Tsunami Warning in Indonesia",
            link: "https://github.com/jeremykenneth7/Tsunami-Warning-Center"
        },
        {
            title: "Tsunami Warning Center 2",
            image: tsunami2,
            description: "Website for Tsunami Disaster and Warning Center with BMKG API on Realtime Earthquake data +5.0 Magnitudo and Realtime Maps with GeoJSON prevention Tsunami Warning in Indonesia",
            link: "https://github.com/jeremykenneth7/Tsunami-Warning-Center"
        },
        {
            title: "Online e-Commerce Website",
            image: onlineshop2,
            description: "🥦 It is an eCommerce app inspired by Tokopedia Website 📱 built to demonstrate the use of web development tools.",
            link: "https://github.com/jeremykenneth7/Online-eCommerce-Website"
        },
        {
            title: "Application Database API Creation",
            image: bangkit,
            description: "API for Calories Application with Database using Express JS and Firebase. For the deployment using Google Cloud Functions",
            link: "https://github.com/CalorEase/CaloriesAPI"
        },
        {
            title: "Machine Learning Model API Creation",
            image: flask,
            description: "API for Machine Learning Model in Calories Application using Flask as a REST-API and for the deployment using Docker and Google Cloud Run",
            link: "https://github.com/jeremykenneth7/CalorEase-API-2"
        },
        {
            title: "Volcano Eruption Prevention Website",
            image: gunung,
            description: "Website for Volcano Eruption Prevention Website in Indonesia with disaster mitigation and feature for searching missing person.",
            link: "https://github.com/jeremykenneth7/Volcano-Eruption-Prevention-Website"
        },
        {
            title: "Website Bimbel Online",
            image: bimbel,
            description: "Website for Online Learning named Belajar Online for helping Indonesia Student study from anywhere",
            link: "#"
        },
        {
            title: "Bookshelf Website",
            image: bookshelf,
            description: "A Frontend Development Website for Bookshelf that connect with Local Storage on Device. Build and Developed with JavaScript",
            link: "https://github.com/jeremykenneth7/BookshelfApps-Frontend-LocalStorage"
        },
    ];

    const mobileProjects = [
        {
            title: "Computer Shop Mobile Application",
            image: computershop,
            description : "A Mobile Development Application for Recommended Places and Stopwatch inside of it. Build and Developed with Flutter",
            link:"https://github.com/jeremykenneth7/Computer-Shop-MobileApps"
        },
        {
            title: "Stopwatch + Recommended Places Mobile Application",
            image: stopwatch,
            description: "A Mobile Development Application for Computer Shop that connect with API and Database. Build and Developed with Flutter",
            link:"https://github.com/jeremykenneth7/StopwatchApp-Flutter"
        },
    ];

    return (
        <div className={darkMode ? "dark" : ""}>
            <Head>
                <title>Jeremy Kenneth Portofolio</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <main className=" bg-white px-10 dark:bg-gray-900 md:px-20 lg:px-40 min-h-screen">

                <nav className="py-5 md:py-10 mb-4 md:mb-12 flex flex-col md:flex-row justify-between dark:text-white">
                    <div className="md:flex md:items-center md:justify-between">
                        {/* Mobile View */}
                        <div className="md:hidden">
                            {/* Home Link */}
                            <Link href="/">
                                <a className="mr-4 font-burtons text-lg py-1 dark:text-white hover:border-teal-500">Jeremy</a>
                            </Link>
                            {/* Portfolio and Certificates Links */}
                            <div className="flex flex-col">
                                <Link href="/portofolio">
                                    <a className="font-burtons text-lg py-1 dark:text-white hover:border-teal-500">Portfolio</a>
                                </Link>
                                <Link href="/certificates">
                                    <a className="font-burtons text-lg py-1 mb-5 dark:text-white hover:border-teal-500">Certificates</a>
                                </Link>
                            </div>
                        </div>

                        {/* Desktop View */}
                        <div className="hidden md:flex md:items-center">
                            {/* Home Link */}
                            <Link href="/">
                                <a className="mr-4 font-burtons text-lg py-1 dark:text-white hover:border-teal-500">Jeremy</a>
                            </Link>
                            {/* Portfolio Link */}
                            <Link href="/portofolio">
                                <a className="ml-8 font-burtons text-3xl py-1 dark:text-white hover:border-teal-500">Portfolio</a>
                            </Link>
                            {/* Certificates Link */}
                            <Link href="/certificates">
                                <a className="ml-8 font-burtons text-3xl py-1 dark:text-white hover:border-teal-500">Certificates</a>
                            </Link>
                        </div>
                    </div>
                    <ul className="flex items-center">
                        <li>
                            <BsFillMoonStarsFill
                                onClick={() => setDarkMode(!darkMode)}
                                className=" cursor-pointer text-2xl"
                            />
                        </li>
                        <li>
                            <a
                                className="bg-gradient-to-r from-blue-500 text- to-yellow-700 text-white px-4 py-2 border-none rounded-md ml-8"
                                href="CV-Jeremy-Kenneth.pdf"
                                alt="alt text"
                                target="_blank"
                                rel="noopener noreferrer"
                            >CV</a>
                        </li>
                        <li>
                            <a
                                className="bg-gradient-to-r from-red-500 text- to-teal-700 text-white px-4 py-2 border-none rounded-md ml-8"
                                href="Resume-Jeremy-Kenneth.pdf"
                                alt="alt text"
                                target="_blank"
                                rel="noopener noreferrer"
                            >Resume</a>
                        </li>
                    </ul>
                </nav>

                <div>
                    <p className="font-mono text-md py-5 leading-8 text-gray-800 dark:text-gray-200 md:text-xl">
                        Crafting a compelling portfolio to showcase my extensive experience in Full-Stack Development + Mobile Development has been a rewarding journey. Through a dynamic blend of creativity and technical prowess, I have meticulously curated a collection of projects that encapsulate my proficiency in crafting seamless application and website. From responsive website that adapt flawlessly to diverse screen sizes to interactive interfaces that engage users intuitively. Each project stands as a testament to my mastery of Flutter, PHP, React JS, Next JS, Laravel and other cutting-edge technologies, which I seamlessly integrate to breathe life into my programming experience.
                    </p>
                </div>
                <div className="flex flex-col gap-10 py-10 lg:flex-row lg:flex-wrap">
                    {/* Display web projects */}
                    {webProjects.map((project, index) => (
                        <div key={index} className="basis-1/4 flex-1">
                            <div className="rounded-lg overflow-hidden shadow-md">
                                <a href={project.link} target="_blank" rel="noopener noreferrer">
                                    <Image
                                        className="rounded-lg overflow-hidden shadow-md"
                                        width={"200%"}
                                        height={"110%"}
                                        layout="responsive"
                                        src={project.image}
                                        alt={project.title}
                                    />
                                </a>
                                <div className="p-5">
                                    <p className="text-center text-gray-700 dark:text-gray-300 mb-1">{project.title}</p>
                                    <p className="text-center text-gray-700 dark:text-gray-300 text-xs font-normal">{project.description}</p>
                                </div>
                            </div>
                        </div>
                    ))}
                </div>
                <div className="flex flex-col gap-10 py-10 lg:flex-row lg:flex-wrap">
                    {/* Display mobile projects */}
                    {mobileProjects.map((project, index) => (
                        <div key={index} className="basis-1/4 flex-1">
                            <div className="rounded-lg overflow-hidden shadow-md">
                                <a href={project.link} target="_blank" rel="noopener noreferrer">
                                    <Image
                                        className="rounded-lg overflow-hidden shadow-md"
                                        width={"200%"}
                                        height={"110%"}
                                        layout="responsive"
                                        src={project.image}
                                        alt={project.title}
                                    />
                                </a>
                                <div className="p-5">
                                    <p className="text-center text-gray-700 dark:text-gray-300 mb-1">{project.title}</p>
                                    <p className="text-center text-gray-700 dark:text-gray-300 text-xs font-normal">{project.description}</p>
                                </div>
                            </div>
                        </div>
                    ))}
                </div>
            </main>
        </div>
    );
}
